# SPDX-FileCopyrightText: © 2025 DSLab - Fondazione Bruno Kessler
# SPDX-FileCopyrightText: © 2026 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

FROM ghcr.io/scc-digitalhub/digitalhub-serverless/python-runtime:3.11-0.15.0b21

RUN pip install task-inference torch>=2.0 transformers==4.42.1 pillow>=10.0.0
