# SPDX-FileCopyrightText: © 2026 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

"""task_inference.tasks - task schemas and abstract base classes."""

from .audio import (
    ASRChunk,
    ASRInput,
    ASROutput,
    ASRTask,
    AudioClassificationInput,
    AudioClassificationOutput,
    AudioClassificationResult,
    AudioClassificationTask,
)
from .base import BaseTask
from .vision import (
    AnonymizationStrategy,
    BoundingBox,
    ClassificationResult,
    DepthEstimationInput,
    DepthEstimationOutput,
    DepthEstimationTask,
    DetectedObject,
    GeneratedMask,
    ImageAnonymizationInput,
    ImageAnonymizationOutput,
    ImageAnonymizationTask,
    ImageClassificationInput,
    ImageClassificationOutput,
    ImageClassificationTask,
    ImageSegmentationInput,
    ImageSegmentationOutput,
    ImageSegmentationTask,
    MaskGenerationInput,
    MaskGenerationOutput,
    MaskGenerationTask,
    ObjectDetectionInput,
    ObjectDetectionOutput,
    ObjectDetectionTask,
    Point,
    SegmentResult,
    VQAAnswer,
    VQAInput,
    VQAOutput,
    VQATask,
    ZeroShotClassificationResult,
    ZeroShotImageClassificationInput,
    ZeroShotImageClassificationOutput,
    ZeroShotImageClassificationTask,
    ZeroShotObjectDetectionInput,
    ZeroShotObjectDetectionOutput,
    ZeroShotObjectDetectionTask,
)

__all__ = [
    "BaseTask",
    # vision
    "AnonymizationStrategy",
    "BoundingBox",
    "ClassificationResult",
    "DepthEstimationInput",
    "DepthEstimationOutput",
    "DepthEstimationTask",
    "DetectedObject",
    "GeneratedMask",
    "ImageAnonymizationInput",
    "ImageAnonymizationOutput",
    "ImageAnonymizationTask",
    "ImageClassificationInput",
    "ImageClassificationOutput",
    "ImageClassificationTask",
    "ImageSegmentationInput",
    "ImageSegmentationOutput",
    "ImageSegmentationTask",
    "MaskGenerationInput",
    "MaskGenerationOutput",
    "MaskGenerationTask",
    "ObjectDetectionInput",
    "ObjectDetectionOutput",
    "ObjectDetectionTask",
    "Point",
    "SegmentResult",
    "VQAAnswer",
    "VQAInput",
    "VQAOutput",
    "VQATask",
    "ZeroShotClassificationResult",
    "ZeroShotImageClassificationInput",
    "ZeroShotImageClassificationOutput",
    "ZeroShotImageClassificationTask",
    "ZeroShotObjectDetectionInput",
    "ZeroShotObjectDetectionOutput",
    "ZeroShotObjectDetectionTask",
    # audio
    "ASRChunk",
    "ASRInput",
    "ASROutput",
    "ASRTask",
    "AudioClassificationInput",
    "AudioClassificationOutput",
    "AudioClassificationResult",
    "AudioClassificationTask",
]
